### ISSUE TITLE
:snowflake: Make better makefile for the project

### ISSUE THREAD

**Issue by 6im0n** [epitech-mirroring/MyPandoc#13]
# 👮‍♂️ What's needed
Add color and status to the make file

## 📋 Subtasks
- [x] Add color to the make file for each status
- [x] Remove the stack error when no error 
- [x] Save the stack error to a log 
- [x] Read the log if error
- [x] Make a rule to read the log if needed

# 📜 Sources
Makefile
