### ISSUE TITLE
🪛 Command argument handling

### ISSUE THREAD

**Issue by 6im0n** [epitech-mirroring/MyPandoc#7]
# 👮‍♂️ What's needed
Parse the command for all the file type. And argument options

## 📋 Subtasks
- [ ] Parse the command
- [ ] Test if the file in the input can be readable
- [ ] For the ouput file create the file
- [ ] input path (Mandatory) to read the data from the right file (ifile)
- [ ] output path (option) to write the data in the right file or standard output
- [ ] output format (Mandatory) to write the right format of data
- [ ] input format (optional) if not launch detection of the format
  

# 📜 Sources
No specific sources
